packages:
  - .
  - docs

# 12 hours
minimumReleaseAge: 720

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
