// This file is auto-generated by prisma/seed.ts. Do not edit manually.
export const SEED_DATA = {
  USER_EMAIL: 'admin@piowsee.com', // Admin email
  REGULAR_USER_EMAIL: 'user@piowsee.com', // Regular user email
  WABA_META_ID: '123456789012345',
  PHONE_META_ID: '979032335300118',
  CUSTOMER_PHONE: '628123456789',
  WEBHOOK_NAME: 'Seed Webhook',
  SYSTEM_USER_TOKEN:
    'enc:U2FsdGVkX1/j+6weFRDhMRnkLKFuZQB+F1O2HKIMSdkRy1WFfsZOTvxSC5T53/u6',
};
