---
- name: Ensure deployment directories exist
  ansible.builtin.file:
    path: '~/pesanai-docker/{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - n8n

- name: Copy n8n files
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/../n8n/'
    dest: '~/pesanai-docker/n8n/'
    mode: '0644'
