---
- name: Pull n8n Image
  ansible.builtin.command: sudo docker compose pull
  args:
    chdir: '~/pesanai-docker/n8n'

- name: Start n8n
  ansible.builtin.command: sudo docker compose up -d
  args:
    chdir: '~/pesanai-docker/n8n'
