---
- name: Pull n8n Nginx Image
  ansible.builtin.command: docker compose pull
  args:
    chdir: '{{ ansible_facts.env.HOME }}/pesanai-docker/nginx'
  become: yes

- name: Start n8n Nginx Proxy
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: '{{ ansible_facts.env.HOME }}/pesanai-docker/nginx'
  become: yes

- name: Reload n8n Nginx configuration
  ansible.builtin.command: docker exec nginx nginx -s reload
  become: yes
  ignore_errors: yes
