[global]
repo1-cipher-pass=
repo1-cipher-type=
repo1-retention-full=
repo1-s3-bucket=
repo1-s3-endpoint=
repo1-s3-key=
repo1-s3-key-secret=
repo1-s3-region=
repo1-type=

[YOUR_STANZA]
pg1-path=/var/lib/postgresql/data
