---
- name: Ensure deployment directories exist
  ansible.builtin.file:
    path: '~/pesanai-docker/{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - app
    - database

- name: Copy App docker-compose
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/../app/docker-compose.yaml'
    dest: '~/pesanai-docker/app/docker-compose.yaml'
    mode: '0644'

- name: Copy App Nginx config
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/../app/nginx.conf'
    dest: '~/pesanai-docker/app/nginx.conf'
    mode: '0644'

- name: Copy Database files
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/../database/'
    dest: '~/pesanai-docker/database/'
    mode: preserve

- name: Inject Domain into Nginx App Config
  ansible.builtin.replace:
    path: '~/pesanai-docker/app/nginx.conf'
    regexp: 'YOUR_DOMAIN_NAME'
    replace: '{{ app_domain_name }}'
