---
- name: Pull App Image
  ansible.builtin.command: docker compose pull
  args:
    chdir: '{{ ansible_facts.env.HOME }}/pesanai-docker/app'
  become: yes

- name: Start App
  ansible.builtin.command: docker compose up -d
  args:
    chdir: '{{ ansible_facts.env.HOME }}/pesanai-docker/app'
  become: yes
