---
- name: Pull App Image
  ansible.builtin.command: sudo docker compose pull
  args:
    chdir: '~/pesanai-docker/app'

- name: Start App
  ansible.builtin.command: sudo docker compose up -d
  args:
    chdir: '~/pesanai-docker/app'
