name: CI
run-name: CI for commit ${{ github.sha }} by @${{ github.actor }}

on:
  pull_request:
    branches: ['main', 'dev']
  push:
    branches: ['main', 'dev']

permissions:
  contents: read

# .env only for CI
env:
  NODE_ENV: test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_DB: testdb
  DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb
  DIRECT_URL: postgresql://testuser:testpassword@localhost:5432/testdb
  ENCRYPTION_KEY: thisisarandom32characters1234567
  DIGITAL_OCEAN_SPACES_BUCKET_NAME=: fake_name
  DIGITAL_OCEAN_SPACES_BUCKET_ENDPOINT: fake_endpoint
  DIGITAL_OCEAN_SPACES_BUCKET_ACCESS_KEY: fake_access_key
  DIGITAL_OCEAN_SPACES_BUCKET_SECRET_KEY: fake_secret_key

jobs:
  web-ci:
    name: CI
    runs-on: blacksmith-4vcpu-ubuntu-2404

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint check
        run: pnpm lint

      - name: Prettier check
        run: pnpm format:check

      - name: Generate prisma
        run: pnpm prisma generate

      - name: Run migration scripts
        run: pnpm prisma migrate dev

      - name: Run db seeding script
        run: pnpm prisma db seed

      - name: Run test scripts
        run: pnpm run test

      - name: Build check
        run: pnpm run build

  # Build job for docs
  docs-build:
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest

    env:
      MDBOOK_VERSION: 0.5.3
      # Update the language picker in head.hbs to link new languages.
      LANGUAGES: id

    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Install mdbook-i18n-helpers
        run: |
          cargo install mdbook-i18n-helpers --locked --version 0.4.0

      - name: Run tests
        run: mdbook test

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build HTML
        run: mdbook build

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir "$(pwd)" --verbose --no-progress './docs/**/*.md' './docs/book/**/*.html'

      - name: Build all translations
        run: |
          for po_lang in ${{ env.LANGUAGES }}; do
            echo "::group::Building $po_lang translation"
            # Set language and adjust site URL. Clear the redirects
            # since they are in sync with the source files, not the
            # translation.
            MDBOOK_BOOK__LANGUAGE=$po_lang \
            mdbook build -d book/$po_lang
            echo "::endgroup::"
          done

      - name: Check all translations for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir "$(pwd)" --verbose --no-progress './docs/book/${{ env.LANGUAGES }}/**/*.html'
