name: CI
run-name: CI for commit ${{ github.sha }} by @${{ github.actor }}

on:
  pull_request:
    branches: ['main', 'dev']
  push:
    branches: ['main', 'dev']

# .env only for CI
env:
  NODE_ENV: test
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_DB: testdb
  DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb
  DIRECT_URL: postgresql://testuser:testpassword@localhost:5432/testdb

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint check
        run: pnpm lint

      - name: Prettier check
        run: pnpm format:check

      - name: Generate prisma
        run: pnpm prisma generate

      - name: Run migration scripts
        run: pnpm prisma migrate dev

      - name: Run db seeding script
        run: pnpm prisma db seed

      - name: Run test scripts
        run: pnpm run test

      - name: Build check
        run: pnpm run build
