name: CI
run-name: CI for commit ${{ github.sha }} by @${{ github.actor }}

on:
  pull_request:
    branches: ['main', 'dev']
  push:
    branches: ['main', 'dev']

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint check
        run: pnpm lint

      - name: Prettier check
        run: pnpm format:check

      - name: Build check
        run: pnpm run build
